modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/Mechalopa/Just-a-Few-Ohana/issues"
[[mods]]
modId="jafohana"
version="1.1.0"
displayName="Just a Few Ohana"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/Mechalopa/Just-a-Few-Ohana"
#logoFile="logo.png"
credits="Mechalopa"
authors="Mechalopa"
description='''More new flowers.'''
itemIcon="jafohana:dayflower"
[[dependencies.jafohana]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jafohana]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"